version: '3.8'
services:
  api:
    container_name: node_assignment
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - DB_HOST=postgres_db
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules

  postgres_db:
    container_name: postgres_db
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -h localhost -p ${DB_PORT} -d ${DB_NAME}'"]
      interval: 3s
      timeout: 5s
      retries: 2

volumes:
 data: {}